name: Build & Push Frontend + Backend Images

on:
  push:
    branches:
      - main
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      run: |
        echo "Logging into Docker Hub"
        echo PASSWORD_HERE | docker login -u ktejaswanth --password-stdin

    - name: Build Frontend Image
      run: |
        docker build -t ktejaswanth/my-frontend:latest ./frontend

    - name: Push Frontend Image
      run: |
        docker push ktejaswanth/my-frontend:latest

    - name: Build Backend Image
      run: |
        docker build -t ktejaswanth/my-backend:latest ./backend

    - name: Push Backend Image
      run: |
        docker push ktejaswanth/my-backend:latest
