name: Build & Push Frontend + Backend Images

on:
  push:
    branches:
      - main
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:

    # Checkout repo
    - name: Checkout code
      uses: actions/checkout@v3

    # Login to Docker Hub
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build & Push Frontend
    - name: Build Frontend Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest ./frontend

    - name: Push Frontend Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest

    # Build & Push Backend
    - name: Build Backend Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-backend:latest ./backend

    - name: Push Backend Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-backend:latest
